version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
    command: "-p ${DB_PORT}"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
  api:
    restart: always
    build:
      context: .
      dockerfile: ./Api/Dockerfile
    ports:
      - "8000:8080"
      - "8001:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      "RabbitMQConnection:Host": "${RABBITMQ_HOST}"
      "RabbitMQConnection:Username": "${RABBITMQ_USER}"
      "RabbitMQConnection:Password": "${RABBITMQ_PASSWORD}"
      "Authorization:URL": "${AUTH_URL}"
  workers:
    restart: always
    build:
      context: .
      dockerfile: ./AbstractTasksWorkers/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      "ConnectionStrings:DefaultConnection": "Host=${DB_HOST}; Port=${DB_PORT}; Database=${DB_DATABASE}; Username=${DB_USERNAME}; Password=${DB_PASSWORD}"
      "RabbitMQConnection:Host": "${RABBITMQ_HOST}"
      "RabbitMQConnection:Username": "${RABBITMQ_USER}"
      "RabbitMQConnection:Password": "${RABBITMQ_PASSWORD}"
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    
volumes:
  db:
    driver: local